.travis.yml: Exclude flake8 for python 2.6
because the latest version of flake8 doesn't work on Python 2.6 and will
fail with:

```
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/utils.py", line 287, in parameters_for
    parameters = collections.OrderedDict([
AttributeError: 'module' object has no attribute 'OrderedDict'
```

e.g.: https://travis-ci.org/JetBrains/teamcity-messages/jobs/148233929